### ISSUE TITLE
Upgrading ESLint Peer Dependency

### ISSUE THREAD

**Issue by RyanMulready** [maranran/eslint-plugin-vue-a11y#4]
We are now using ESLint 5 regularly.  Anything preventing you from upgrading or at the very least upgrading the peer dependency to include both?

**Comment by maranran** [comment]
done @RyanMulready

**Comment by RyanMulready** [comment]
Nice.

**Comment by goatandsheep** [comment]
I am still having an issue since `estlint-plugin-vue@4.4.0` only supports `eslint@^3.18.0 || ^4.0.0`. Can we upgrade to `eslint-plugin-vue@^5.0.0`?
